In [1]:
import pandas as pd

In [5]:
df=pd.read_csv("Book1.csv")
df

       NAME  AGE  SCORES
0    Sakshi   21      71
1     Suman   23      75
2     Nitin   18      70
3    Shreya   22      72
4      Neha   19      76
5     Parul   25      79
6  Abhishek   24      78

In [6]:
df.head()

     NAME  AGE  SCORES
0  Sakshi   21      71
1   Suman   23      75
2   Nitin   18      70
3  Shreya   22      72
4    Neha   19      76

In [16]:
df.tail(3)

       NAME  AGE  SCORES
4      Neha   19      76
5     Parul   25      79
6  Abhishek   24      78

In [13]:
df.shape

(7, 3)

In [15]:
df.describe

<bound method NDFrame.describe of        NAME  AGE  SCORES
0    Sakshi   21      71
1     Suman   23      75
2     Nitin   18      70
3    Shreya   22      72
4      Neha   19      76
5     Parul   25      79
6  Abhishek   24      78>

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NAME    7 non-null      object
 1   AGE     7 non-null      int64
 2   SCORES  7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [18]:
df["SCORES"]=df["SCORES"]+1

In [19]:
df["SCORES"]

0    72
1    76
2    71
3    73
4    77
5    80
6    79
Name: SCORES, dtype: int64