In [1]:
import pandas as pd

In [2]:
df = pd.read_csv ("sample_dirty_dataset.csv")
df

    ID    Name   Age       City   Salary Department   Join_Date
0   12  Suresh  28.0    Chennai  61000.0    Finance  2022-04-04
1    5   Sneha  35.0    Chennai  50000.0         IT  2023-05-05
2    6    Neha   NaN       Pune      NaN        NaN  2021-08-19
3    1  Vikram  22.0      Delhi  25000.0      Sales  2021-03-01
4   10   Karan  27.0     Mumbai      NaN        NaN  2019-06-25
5    4   Sneha  30.0        NaN  45000.0  Marketing  2019-11-20
6    2   Pooja  25.0     Mumbai  30000.0         IT  2020-07-15
7   11   Pooja   NaN       Pune  52000.0         IT  2021-12-12
8    8   Pooja  19.0      Delhi  80000.0      Sales  2022-09-30
9    2   Pooja  25.0     Mumbai  30000.0         IT  2020-07-15
10   3   Rohan   NaN  Bangalore      NaN         HR  2022-01-10
11   7    Neha  40.0    Kolkata  75000.0    Finance  2020-02-14
12   8   Pooja  19.0      Delhi  80000.0      Sales  2022-09-30
13   5   Sneha  35.0    Chennai  50000.0         IT  2023-05-05
14   9    Neha  23.0        NaN  28000.0         HR  2023-01-01

In [3]:
print(df.shape)

(15, 7)

In [4]:
print(df.duplicated().sum())
print(df.isnull().sum())

3
ID            0
Name          0
Age           3
City          2
Salary        3
Department    2
Join_Date     0
dtype: int64

In [5]:
# to remove duplicates
df = df.drop_duplicates()

In [6]:
# to handle missing values
df = df.copy()
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Salary"] = df["Salary"].fillna(df["Salary"].median())
df["City"] = df["City"].fillna(df["City"].mode()[0])
df["Department"] = df["Department"].fillna(df["Department"].mode()[0])

In [7]:
df

    ID    Name        Age       City   Salary Department   Join_Date
0   12  Suresh  28.000000    Chennai  61000.0    Finance  2022-04-04
1    5   Sneha  35.000000    Chennai  50000.0         IT  2023-05-05
2    6    Neha  27.666667       Pune  50000.0         IT  2021-08-19
3    1  Vikram  22.000000      Delhi  25000.0      Sales  2021-03-01
4   10   Karan  27.000000     Mumbai  50000.0         IT  2019-06-25
5    4   Sneha  30.000000    Chennai  45000.0  Marketing  2019-11-20
6    2   Pooja  25.000000     Mumbai  30000.0         IT  2020-07-15
7   11   Pooja  27.666667       Pune  52000.0         IT  2021-12-12
8    8   Pooja  19.000000      Delhi  80000.0      Sales  2022-09-30
10   3   Rohan  27.666667  Bangalore  50000.0         HR  2022-01-10
11   7    Neha  40.000000    Kolkata  75000.0    Finance  2020-02-14
14   9    Neha  23.000000    Chennai  28000.0         HR  2023-01-01